# Uncomment the next line to define a global platform for your project
  platform :ios, '13.0'

target 'MVVM-JSON' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM-JSON
    pod 'Alamofire'

  target 'MVVM-JSONTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVM-JSONUITests' do
    # Pods for testing
  end

end
